/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 ./src/assets/scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} color="#a3946c" position={[-190.882, 302.753, 108.161]} />
      <PerspectiveCamera makeDefault={false} far={1000.04} position={[294.113, 269.108, 409.377]} rotation={[-0.557, 0.654, 0.362]} />
      <group scale={0.01}>
        <mesh geometry={nodes.Windows_Material__4053_0.geometry} material={materials.Material__4053} position={[5704.957, 16957.371, 11647.982]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.FireExtinguishers_Material__4051_0.geometry} material={materials.Material__4051} position={[12.567, 14841.255, 5289.227]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Body_Material__4041_0.geometry} material={materials.Material__4041} position={[-354.995, 10261.182, 3439.871]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Platform_Material__4045_0.geometry} material={materials.Material__4045} position={[-832.162, 10136.021, 16143.405]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Trim_Material__4046_0.geometry} material={materials.Material__4046} position={[1826.256, 13367.258, 12331.716]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Chassis_Material__4043_0.geometry} material={materials.Material__4043} position={[25.341, 10411.041, 3100.883]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Tires_Material__4040_0.geometry} material={materials.Material__4040} position={[6.141, 5522.369, -5855.496]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.SeatsLights_Material__4049_0.geometry} material={materials.Material__4049} position={[778.855, 13537.125, 12107.189]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Part05_Material__4048_0.geometry} material={materials.Material__4048} position={[-195.327, 12475.196, 14126.983]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
