# on:
#   push:
#     branches:
#       - develop
# name: 🚀 Deploy test website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v2

#       - name: Setup Node
#         uses: actions/setup-node@v3

#       - name: Install dependencies
#         uses: bahmutov/npm-install@v1

#       - name: Build project
#         run: npm run build

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v3
#         with:
#           name: production-files
#           path: ./dist

#       - name: 📂 Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with:
#           server: ${{ secrets.ftp_host }}
#           username: ${{ secrets.ftp_user }}
#           password: ${{ secrets.ftp_password }}
#           server-dir: /public_html/

#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: production-files
#           path: ./dist

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist
